import "./globals.css";
import QueryProvider from "@/provider/QueryProvider";
import LayoutWrapper from "@/components/LayoutWrapper";

export const metadata = {
  title: "next revision",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <QueryProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
